"""Generate fixtures/sample_frames.json — a synthetic but schema-exact Activity Frames
document used for development, tests and the no-Mac demo mode.

Replace it with a real recording as soon as capture works:
    aframes day <YYYY-MM-DD> -f json > fixtures/sample_frames.json

Scenario (one evening):
  19:30-19:44  LeetCode "Two Sum"           -> solved quickly, not stuck
  19:46-20:10  VS Code project + localhost  -> normal project work
  20:12-20:46  LeetCode "Coin Change"       -> stuck: long, low typing, 3 help loops
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path

DAY = "2026-10-08"
OUT = Path(__file__).resolve().parent.parent / "fixtures" / "sample_frames.json"

# (app, site, start, end, window, pages, keys, clicks)
SCRIPT = [
    ("Google Chrome", "leetcode.com", "19:30:05", "19:41:40", "1. Two Sum - LeetCode",
     [{"kind": "page", "entity": "problems"}], 610, 44),
    ("Google Chrome", "leetcode.com", "19:41:40", "19:44:10", "Two Sum - Submissions - LeetCode",
     [{"kind": "page", "entity": "problems"}], 12, 9),
    ("Code", None, "19:46:00", "19:58:30", "app.py — todo-api — Visual Studio Code",
     [], 780, 52),
    ("Google Chrome", "localhost", "19:58:30", "20:00:10", "Todo API",
     [{"kind": "local_dev", "entity": "localhost:5173"}], 4, 11),
    ("Code", None, "20:00:10", "20:10:20", "routes.py — todo-api — Visual Studio Code",
     [], 640, 38),
    ("Google Chrome", "leetcode.com", "20:12:00", "20:20:10", "322. Coin Change - LeetCode",
     [{"kind": "page", "entity": "problems"}], 58, 21),
    ("Google Chrome", "stackoverflow.com", "20:20:10", "20:24:00",
     "dynamic programming - Coin change minimum coins - Stack Overflow",
     [{"kind": "question", "entity": "coin-change-minimum-coins"}], 6, 14),
    ("Google Chrome", "leetcode.com", "20:24:00", "20:29:15", "322. Coin Change - LeetCode",
     [{"kind": "page", "entity": "problems"}], 39, 17),
    ("Google Chrome", "chatgpt.com", "20:29:15", "20:33:05", "ChatGPT",
     [{"kind": "ai_chat"}], 61, 6),
    ("Google Chrome", "leetcode.com", "20:33:05", "20:38:20", "322. Coin Change - LeetCode",
     [{"kind": "page", "entity": "problems"}], 44, 19),
    ("Google Chrome", "google.com", "20:38:20", "20:41:10", "coin change dp explanation - Google Search",
     [{"kind": "search", "entity": "coin change dp explanation"}], 27, 8),
    ("Google Chrome", "leetcode.com", "20:41:10", "20:46:30", "322. Coin Change - LeetCode",
     [{"kind": "page", "entity": "problems"}], 31, 12),
]


def _minutes(start: str, end: str) -> float:
    fmt = "%H:%M:%S"
    return round((datetime.strptime(end, fmt) - datetime.strptime(start, fmt)).total_seconds() / 60, 1)


def build() -> dict:
    frames = []
    row = 100_000
    for i, (app, site, start, end, window, pages, keys, clicks) in enumerate(SCRIPT, start=1):
        dur = _minutes(start, end)
        n_rows = max(3, int(dur * 6))          # ~1 snapshot / 10 s
        frame = {"id": f"f-{i:04d}", "app": app}
        if site:
            frame["site"] = site
        frame.update(start=start, end=end, duration_min=dur, windows=[window])
        if pages:
            frame["pages"] = pages
        frame["input"] = {"keys": keys, "clicks": clicks}
        frame["evidence"] = {"frame_ids": f"{row}..{row + n_rows - 1}"}
        row += n_rows
        frames.append(frame)

    return {
        "schema_version": 1,
        "_synthetic": True,
        "_note": "Synthetic development fixture in Activity Frames schema v1. "
                 "Replace with a real recording (aframes day <date> -f json).",
        "generated_at": f"{DAY}T15:20:00Z",
        "source": {"recorder": "synthetic"},
        "window": {"day": DAY},
        "coverage": {"first_activity": "19:30", "last_activity": "20:46"},
        "frames": frames,
        "blind_spots": [
            "Synthetic data: generated by scripts/make_fixture.py, not recorded.",
        ],
    }


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
